package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

var names = []struct {
	csharp string
	goName string
}{
	{"NOCover", "originalNoCover"},
	{"stylecss", "originalStyleCSS"},
	{"scriptjs", "originalScriptJS"},
	{"offlivecss", "originalOffLiveCSS"},
	{"livecss", "originalLiveCSS"},
}

func main() {
	source := filepath.Join("..", "DDBOT", "ImageHelper.cs")
	target := filepath.Join("internal", "render", "original_templates.go")

	data, err := os.ReadFile(source)
	if err != nil {
		fatal(err)
	}

	var out strings.Builder
	out.WriteString("package render\n\n")
	out.WriteString("// Code generated by tools/extracttemplates from DDBOT/ImageHelper.cs; DO NOT EDIT.\n\n")

	text := string(data)
	for _, name := range names {
		value, err := csharpString(text, name.csharp)
		if err != nil {
			fatal(err)
		}
		out.WriteString("const ")
		out.WriteString(name.goName)
		out.WriteString(" = ")
		out.WriteString(strconv.Quote(value))
		out.WriteString("\n\n")
	}

	if err := os.WriteFile(target, []byte(out.String()), 0o644); err != nil {
		fatal(err)
	}
}

func csharpString(data, name string) (string, error) {
	marker := "public static string " + name
	start := strings.Index(data, marker)
	if start < 0 {
		return "", fmt.Errorf("cannot find %s", name)
	}
	eq := strings.IndexByte(data[start:], '=')
	if eq < 0 {
		return "", fmt.Errorf("cannot find assignment for %s", name)
	}
	i := start + eq + 1
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\r' || data[i] == '\n') {
		i++
	}

	verbatim := false
	if i < len(data) && data[i] == '@' {
		verbatim = true
		i++
	}
	if i >= len(data) || data[i] != '"' {
		return "", fmt.Errorf("%s is not a string literal", name)
	}
	i++

	var b strings.Builder
	for i < len(data) {
		ch := data[i]
		i++

		if verbatim {
			if ch == '"' {
				if i < len(data) && data[i] == '"' {
					b.WriteByte('"')
					i++
					continue
				}
				return b.String(), nil
			}
			b.WriteByte(ch)
			continue
		}

		if ch == '"' {
			return b.String(), nil
		}
		if ch != '\\' {
			b.WriteByte(ch)
			continue
		}
		if i >= len(data) {
			return "", fmt.Errorf("unterminated escape in %s", name)
		}
		esc := data[i]
		i++
		switch esc {
		case '\'', '"', '\\':
			b.WriteByte(esc)
		case '0':
			b.WriteByte(0)
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'v':
			b.WriteByte('\v')
		default:
			b.WriteByte('\\')
			b.WriteByte(esc)
		}
	}
	return "", fmt.Errorf("unterminated string literal for %s", name)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
